-- Ubicaciones
INSERT INTO ubicaciones (edificio, numero, descripcion) VALUES
                                                            ('Casa Navarro', 1, NULL),
                                                            ('Ed Fernando Barón, SJ', 2, NULL),
                                                            ('Ed Gabriel Giraldo, SJ', 3, NULL),
                                                            ('Ed Gerardo Arango Puerta, SJ', 4, NULL),
                                                            ('Talleres de Diseño Industrial', 5, NULL),
                                                            ('Ed Lorenzo Uribe, SJ', 7, NULL),
                                                            ('Ed Ático', 8, NULL),
                                                            ('Ed Julio Carrizosa', 9, NULL),
                                                            ('Ed José Gabriel Maldonado SJ, oficinas', 11, NULL),
                                                            ('Ed José Gabriel Maldonado SJ, laboratorios', 12, NULL),
                                                            ('Ed Leopoldo Rother', 15, NULL),
                                                            ('Ed Carlos Arbeláez Camacho', 16, NULL),
                                                            ('Capilla Nuestra Señora del Camino', 17, NULL),
                                                            ('Talleres de Arquitectura', 18, NULL),
                                                            ('Ed Jorge Hoyos Vásquez, SJ', 20, NULL),
                                                            ('Ed Emilio Arango, SJ', 21, NULL),
                                                            ('Cafetería Central', 23, NULL),
                                                            ('Hospital Universitario San Ignacio', 24, NULL),
                                                            ('Facultad de Educación', 25, NULL),
                                                            ('Facultad de Odontología - Clínicas Odontológicas', 26, NULL),
                                                            ('Ed José del Carmen Acosta', 27, NULL),
                                                            ('Ed Jesús María Fernández, SJ', 28, NULL),
                                                            ('Urgencias HUSI', 29, NULL),
                                                            ('Ed Néstor Santacoloma', 30, NULL),
                                                            ('Ed Rafael Barrientos Conto, Morfología', 31, NULL),
                                                            ('Intituto de Genética Humana', 32, NULL),
                                                            ('Auditorio Alejandro Novoa, SJ', 34, NULL),
                                                            ('Central de Vigilancia', 35, NULL),
                                                            ('Ed Pablo VI', 41, NULL),
                                                            ('Facultad de Artes Ala Oriental', 42, NULL),
                                                            ('Ed Catalán', 43, NULL),
                                                            ('Salones Carrera de Estudios Musicales', 44, NULL),
                                                            ('Capilla San Francisco Javier', 45, NULL),
                                                            ('Ed Cataluña', 46, NULL),
                                                            ('Ed Quindío', 47, NULL),
                                                            ('Ed Juniorado, Bienestar', 48, NULL),
                                                            ('Auditorio Félix Restrepo', 49, NULL),
                                                            ('Ed Félix Restrepo, SJ', 50, NULL),
                                                            ('Ed Angel Valtierra, SJ', 51, NULL),
                                                            ('Ed Carlos Ortiz, SJ', 52, NULL),
                                                            ('Ed Jesús Emilio Ramírez, SJ (Ala este)', 53, NULL),
                                                            ('Ed Jesús Emilio Ramírez, SJ (Ala oeste)', 54, NULL),
                                                            ('Ed Bioterio y Colecciones Biológicas', 55, NULL),
                                                            ('Ed José Rafael Arboleda, SJ', 67, NULL),
                                                            ('Cancha de Fútbol', 90, NULL),
                                                            ('Centro Javeriano de Formación Deportiva', 91, NULL),
                                                            ('Ed Pedro Arrupe, SJ', 94, NULL),
                                                            ('Ed Manuel Briceño Jáuregui, SJ', 95, NULL),
                                                            ('Ed Don Guillermo Castro', 115, NULL),
                                                            ('Ed Hernando Arellano Ángel', 116, NULL);